### ISSUE TITLE
Angular navbar and list components enhancements

### ISSUE THREAD

**Issue by dariusdv** [spring-petclinic/spring-petclinic-angular#121]
I would like to make some enhancements to the Angular project, mainly I would like to update the following:
- add icons for all nav tabs
- center the content inside the "welcome" component
- make the footer fixed at the bottom of the page. This will improve the look of the website when the user is switching between different nab tabs. The footer will no longer jump up and down when the data for the tables is being fetched.
- add some padding-left to the navbar brand
- only show the "Home" and "Add" buttons on the list components after the data from the backend has been received. This will ensure that the "Home" and "Add" buttons will be displayed at their final position on the page, instead of jumping down after the table data has been fetched.

![home_page](https://github.com/spring-petclinic/spring-petclinic-angular/assets/44746797/f2771d1f-55ad-48a3-82c9-a9732f4131b6)

**Comment by arey** [comment]
Hi @dariusdv 
Thanks you for your proposition. I m agréé for thèse enhancements. I propose you open à PR for each one.

**Comment by dariusdv** [comment]
Hi @arey
I created a new pull request for the first part of the changes (navbar, footer and welcome page). https://github.com/spring-petclinic/spring-petclinic-angular/pull/122
There will be a second pull request which will contain the changes for the "Home" and "Add" buttons on the list components.
