### ISSUE TITLE
Use a datepicker for date input

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#14]
For validation purpose and a better user experience, I think it could be interesting to add a datepicker.
I've tried to integrate this one: https://github.com/ng2-ui/datetime-picker but I failed.

**Comment by vfedoriv** [comment]
I think about it:
https://github.com/angular/material2/issues/675

**Comment by arey** [comment]
Does Material Design components for Angular are compatible with Bootstrap?

**Comment by vfedoriv** [comment]
I've tried add this component:
https://github.com/Promact/md2/tree/master/src/lib/datepicker
![screen1](https://cloud.githubusercontent.com/assets/11440242/24631556/7321f7bc-18c9-11e7-9230-18a76f1c377e.png)
But returning value in Date format, so I cannot bind it directly.

**Comment by vfedoriv** [comment]
Datepicker now added to visit-add and visit-edit components.

**Comment by vfedoriv** [comment]
added to pet-add and pet-edit components.

**Comment by vfedoriv** [comment]
Added datepicker from Material Design components for Angular [https://material.angular.io](url)
