### ISSUE TITLE
Upgrade to Angular 4

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#15]
By the way, we may rename this repo to spring-petclinic-angular and spring-petclinic-angular1 to spring-petclinic-angularjs

**Comment by vfedoriv** [comment]
Done. 
Need update readme etc...

**Comment by arey** [comment]
But do you have upgrade the version from 2 to 4 ?

**Comment by arey** [comment]
I've renamed the spring-petclinic-angularjs repo

**Comment by vfedoriv** [comment]
package.json already upgraded to Angular 4.0 version.

**Comment by arey** [comment]
Great. I've didn't see it.

**Comment by vfedoriv** [comment]
Done. 
And added travis config.
