### ISSUE TITLE
ERROR in AppModule is not an NgModule

### ISSUE THREAD

**Issue by ChwingWong** [spring-petclinic/spring-petclinic-angular#17]
`f:\Java\projects\learning\spring-petclinic-angular>npm ls typescript
spring-petclinic-angular@0.1.0 f:\Java\projects\learning\spring-petclinic-angular
+-- @angular/cli@1.0.6 -> f:\Java\projects\learning\spring-petclinic-angular\node_modules\_@angular_cli@1.0.6@@angular\cli
| +-- @ngtools/webpack@1.3.3
| | `-- typescript@2.2.2  extraneous
| `-- typescript@2.2.2
`-- typescript@2.3.3  -> f:\Java\projects\learning\spring-petclinic-angular\node_modules\_typescript@2.3.3@typescript extraneous

npm ERR! extraneous: typescript@2.3.3 f:\Java\projects\learning\spring-petclinic-angular\node_modules\typescript
npm ERR! extraneous: typescript@2.2.2 f:\Java\projects\learning\spring-petclinic-angular\node_modules\@ngtools\webpack\node_modules\typescript`

我需要把package.json里的dependencies的"typescript": "^2.2.2"改成"typescript": "~2.2.2"才可以

**Comment by vfedoriv** [comment]
Not sure I understand you problem...
You trying compile project with typescript 2.3.3 ?
angular-cli 1.0.x not support TS 2.3
https://github.com/angular/angular-cli/issues/6425

**Comment by ChwingWong** [comment]
##Versions:
*@angular/cli: 1.0.6
*npm: 3.10.10
*Node: v6.10.3
##Run
 `git clone https://github.com/spring-petclinic/spring-petclinic-angular.git`
 `cd spring-petclinic-angular`
 `npm install`
 `ng serve`
now log :
`ERROR in AppModule is not an NgModule` 

package.json
`"dependencies": { ..., "typescript": "^2.2.2",...}`
change to 
`"dependencies": { ..., "typescript": "~2.2.2",...}`

run again. It is OK.

Think you. I just got in touch front framework. The project has been help to me。
Do you have any recommendations about  learning Integration project of spring and angular.

----Sorry. I used Baidu translate

**Comment by vfedoriv** [comment]
Well, in fact, we don't need this dependencies in "dependencies" section.
just remove this strings
    "@angular/compiler-cli": "^4.0.1"
...
    "typescript": "^2.2.2"
All should work w/o this strings.

**Comment by ChwingWong** [comment]
Without this this dependencies in "dependencies" section, how can the project find dependencies?
I try to  remove  this string, then `ng serve` 
error :
    The "@angular/compiler-cli" package was not properly installed.

**Comment by vfedoriv** [comment]
Do you have angular CLI globally installed ?
npm install -g @angular/cli
