### ISSUE TITLE
Upgrade to Angular 5

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#18]

**Comment by vfedoriv** [comment]
current datepicker library [https://github.com/Promact/md2/tree/master/src/lib/datepicker](url) doesn't support Angular 5

**Comment by arey** [comment]
I don't a lot of activity and there is no issue about angular 5 support. Do we have to choose another library?

**Comment by vfedoriv** [comment]
yes, maybe from Material Design for Angular [https://github.com/angular/material2](url)

**Comment by vfedoriv** [comment]
updated. seems like work for me.
