### ISSUE TITLE
Security vulnerability in handlebars

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#20]
Notification sent by GitHub:

Known moderate severity security vulnerability detected in handlebars < 4.0.0defined in package-lock.json.package-lock.json update suggested: handlebars ~> 4.0.0.Always verify the validity and compatibility of suggestions with your codebase. | Known moderate severity security vulnerability detected in handlebars < 4.0.0defined in package-lock.json. | package-lock.json update suggested: handlebars ~> 4.0.0. | Always verify the validity and compatibility of suggestions with your codebase.
Known moderate severity security vulnerability detected in handlebars < 4.0.0defined in package-lock.json.
package-lock.json update suggested: handlebars ~> 4.0.0.
Always verify the validity and compatibility of suggestions with your codebase.

[Review vulnerable dependencies](http://sgmail.githubmail.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBkImHLo8piZ8xIuEcRPLQ4Ykc82O3-2B2QkDRkGIB06mqLTpoCmmxNBDFchKxMb5yI0oUzOa4V0Qx2sWuTGALOHj753tSVHCxnrmVq3eMO8V-2Bu_67mByWeqTTAIsjjU-2FzVS1H3-2F2OMy4YIiWvM78Nm7vJxjkFxfwFbhpR-2BZqzOgc03RRAtgo-2FImwk76sZSKwwLs3Um0ALFEBBH6zERezK-2FePp6raB9PW16TJUXS-2FkDyHn0t9t0FS4t00vgBWkyIuzdq8ZBvDcDkGUZxdI2C9kGacliepubYBk5gmGRv78l9IfwdnA5k1ViYY3drfwwcoNxbgU87z8G7jdjV5BYDXd7EttI-3D)

**Comment by vfedoriv** [comment]
I just removed this file.

**Comment by arey** [comment]
Thank you Vitaliy
