### ISSUE TITLE
Images request doesn't take intro consideration base href

### ISSUE THREAD

**Issue by aistoica** [spring-petclinic/spring-petclinic-angular#21]
I have a problem when creating the bundle for it to be deployed on a HTTP server. 

The index.html page is located at: http://localhost:63342/spring-petclinic-angular/dist/index.html
The request to all js files is sent relative to this url setting the base href to ./
The request to the images files is sent to
http://localhost:63342/assets/images/angular.png

Notice the relative path is not used.

To make the bundle I am using the following commands:
ng build --prod --base-href=./ --deploy-url=./

**Comment by vfedoriv** [comment]
For example, Angular app + Nginx config (for CentOS installation):

1. Build Angular application:

  ng build --prod --base-href=/petclinic/ --deploy-url=/petclinic/

2. Create sub-directory **/petclinic** in default nginx directory **/usr/share/nginx/html**

3. Copy **/dist**  sub-directory from Angular appication to  **/usr/share/nginx/html/petclinic**

4. Edit nginx config (nginx.conf file in /etc/nginx/ directory)

```
server {
	listen       80 default_server;
        root         /usr/share/nginx/html;
        index index.html;

	location /petclinic/ {
                alias /usr/share/nginx/html/petclinic/dist/;
                try_files $uri$args $uri$args/ /petclinic/index.html;
        }
}
```

5. Reload nginx:  **nginx -s reload**

6. Run app in brouser:  http://server_name/petclinic/
