### ISSUE TITLE
Form data validation not implemented

### ISSUE THREAD

**Issue by vfedoriv** [spring-petclinic/spring-petclinic-angular#5]
Form data validation not implemented

**Comment by arey** [comment]
@vfedoriv I may work on it

**Comment by arey** [comment]
Owner page validation is available on PR #9

**Comment by vfedoriv** [comment]
work ok, thanks

**Comment by simrin051** [comment]
@arey @vfedoriv 
Can i take up this issue

**Comment by arey** [comment]
Sure @simrin051 you may submit a Pull Request

**Comment by simrin051** [comment]
Hi @arey 

Sorry .. It looks like event form validation to vet page is also done.. Seeing your comment that form validation for owners edit page is completed , I thought for vet page it is incomplete..I noticed that for vet page also it is complete.

![image](https://user-images.githubusercontent.com/26873360/133888887-9cc10a3d-fc82-4dd2-b8de-63c544d4bb80.png)

**Comment by arey** [comment]
@simrin051 do you have check if validation have been implemented for all forms?
If true, we could close this issue.

**Comment by simrin051** [comment]
For owners and vets it is added. I can add for pets and specialties

**Comment by arey** [comment]
Close by https://github.com/spring-petclinic/spring-petclinic-angular/pull/64
