### ISSUE TITLE
Migrating from TSLint to ESLint

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#76]
TSLint has been deprecated since 2019.
 See a migration guide : https://blog.ninja-squad.com/2021/03/31/migrating-from-tslint-to-eslint/

See comment posted by @simrin051 in https://github.com/spring-petclinic/spring-petclinic-angular/pull/74#issuecomment-967197744_

**Comment by simrin051** [comment]
i will take up this issue @arey as it is needed to pass merge my request

**Comment by arey** [comment]
Thanks to https://github.com/spring-petclinic/spring-petclinic-angular/pull/78
