### ISSUE TITLE
Align with new backend API

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-angular#79]
The PR https://github.com/spring-petclinic/spring-petclinic-rest/pull/52 introduce some changes to the backend API: 

- date format have changed to RFC-3339
- some bidirectional ids have been removed. 
- search by lastname API has changed
- The `/pets` resource move to `/owners/{ownerId}/pets`
- Validation rules are not the same (see https://github.com/spring-petclinic/spring-petclinic-angular/pull/142)

Thoses changes may be reported to the Angular frontend.

**Comment by arey** [comment]
@simrin051 you may take this issue if you want

**Comment by simrin051** [comment]
Thanks @arey

**Comment by gerardorosiles** [comment]
Hi, not sure if issue is related to what I am seeing using the Docker image for the Angular frontend. I get 400 response error for the backend endpoints to add a veterinarian, a new type of pet and a new type of speciality.

**Comment by arey** [comment]
Close with https://github.com/spring-petclinic/spring-petclinic-rest/issues/147
