### ISSUE TITLE
Create primefaces fork for spring-petclinic

### ISSUE THREAD

**Issue by vdtidake** [spring-petclinic/spring-petclinic-angular#97]
I am looking to contribute to develop a [primefaces ](https://www.primefaces.org/showcase/index.xhtml?jfwid=d372f)version of spring-petclinic. Let me know your views on this.

**Comment by arey** [comment]
Hi @vdtidake  I would be happy to welcome a new fork to the Spring Petclinic community
I recommand you to start form the canonical version https://github.com/spring-projects/spring-petclinic by forking it and replace the `thymeleaf` layer by `primefaces`.
For my part, I could create a new git repository named `spring-petclinic-primefacers` in this organization.

**Comment by arey** [comment]
Hi @vdtidake sorry for the delay. I don't know if you are always intersted by creating a primefaces fork. Let me know

**Comment by arey** [comment]
Please let us know @vdtidake
